
package:
  name: finite_state_machine_gui_constructor
  version: 1.0.0

source:
  git_rev: 1.0.0
  git_url: https://github.com/georgedimitriadis/FiniteStateMachineMaker_GUI

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - dearpygui
    - jsonpickle
    - functools

test:
  imports:
    -

about:
  home: https://github.com/georgedimitriadis/FiniteStateMachineMaker_GUI
  license: BSD
  license_family: BSD
  summary: A GUI that allows the automatic authoring of finite state machine scripts based on the python-statemachine package (https://pypi.org/project/python-statemachine/)
